### PR TITLE
Add a stick to stain_brush recipe.

### PR DESCRIPTION
**Pull request by Megaf**
So it don't conflict with the mod tapestry.

### CODE REVIEW

**Comment by ssieb** [comment]
I'm sorry.  I still have a half-finished patch to convert this mod to use the mypaint mod for colouring the pieces.  I will finish that this week.

**Comment by Megaf** [comment]
@ssieb Ok, let's just keep this open until you finish the patch then. Thanks for your work!

**Comment by sofar** [comment]
ping @ssieb :)

Would be nice if you could get some time to do what you started!

**Comment by Megaf** [comment]
Yay! Thanks @DonBatman

**Pull request merged**
